# Generated by Django 2.0.2 on 2018-02-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='time',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='facility',
            name='Hosp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Hospital'),
        ),
    ]
