# Generated by Django 2.0.2 on 2018-02-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_auto_20180211_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_ID', models.CharField(max_length=300)),
                ('Quantity_available', models.IntegerField()),
                ('name_of_med', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom_name', models.CharField(max_length=200)),
                ('symptom_ID', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ward_Availability', models.BooleanField(default='False')),
                ('ward_number', models.CharField(max_length=15)),
                ('floor_number', models.CharField(max_length=5)),
                ('Hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='facility',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='faci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Facility'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Profile'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='faciky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Facility'),
        ),
    ]
