# Generated by Django 2.0.2 on 2018-02-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_auto_20180211_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='faci',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='user_ID',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
